eurekaserver:
   image:   tmx-eurekasvr:chapter5
   ports:
       - "8761:8761"

configserver:
    image: tmx-confsvr:chapter5
    ports:
       - "8888:8888"
    links:
       - "eurekaserver:eurekaserver"
    environment:
       EUREKASERVER_URI: "http://eurekaserver:8761/eureka/"

database:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=p0stgr@s
      - POSTGRES_DB=eagle_eye_local

licensingservice:
    image: tmx-licensing-service:chapter5
    ports:
      - "8080:8080"
      - "8090:8090"
    links:
      - "database:database"
      - "configserver:configserver"
      - "eurekaserver:eurekaserver"
    environment:
      PROFILE: "default"
      SERVER_PORT: "8080"
      CONFIGSERVER_URI: "http://configserver:8888"
      EUREKASERVER_URI: "http://eurekaserver:8761/eureka/"

organizationservice:
    image: tmx-organization-service:chapter5
    ports:
      - "8085:8085"
    links:
      - "database:database"
      - "configserver:configserver"
      - "eurekaserver:eurekaserver"
    environment:
      PROFILE: "default"
      SERVER_PORT: "8085"
      CONFIGSERVER_URI: "http://configserver:8888"
      EUREKASERVER_URI: "http://eurekaserver:8761/eureka/"
