database:
  extends:
    file: ../common/docker-compose.yml
    service: database
  environment:
    - POSTGRES_USER=postgres_dev
    - POSTGRES_PASSWORD=p0stgr@s_dev
    - POSTGRES_DB=eagle_eye_dev

configserver:
  extends:
    file: ../common/docker-compose.yml
    service: configserver

licensingservice:
    image: ch3-thoughtmechanix/licensing-service
    ports:
      - "8080:8080"
    links:
      - "database:database"
      - "configserver:configserver"
    environment:
      PROFILE: "dev"
      CONFIGSERVER_URI: "http://configserver:8888"
