language:  java
jdk:
  - oraclejdk8
notifications:
  slack: teamcarnell:zhTADgjsb7yJ5RPEd7LPNFwI
  email:
    - carnell28@gmail.com
  on_success: always
  on_failure: always 
env:
  - TEST_DIR=chapter2-code
  - TEST_DIR=chapter3-code/confsvr
  - TEST_DIR=chapter3-code/licensing-service
  - TEST_DIR=chapter4-code/confsvr
  - TEST_DIR=chapter4-code/eurekasvr
  - TEST_DIR=chapter4-code/licensing-service
  - TEST_DIR=chapter4-code/organization-service
script: cd $TEST_DIR && mvn clean package
