language: java
cache:
  directories:
  - $HOME/.m2
jdk:
- oraclejdk8
sudo: required
services:
- docker
notifications:
  slack: teamcarnell:zhTADgjsb7yJ5RPEd7LPNFwI
  email:
  - carnell28@gmail.com
  on_success: always
  on_failure: always
env:
  matrix:
  - TEST_DIR=chapter2-code
  - TEST_DIR=chapter3-code/confsvr
  - TEST_DIR=chapter3-code/licensing-service
  - TEST_DIR=chapter4-code/confsvr
  - TEST_DIR=chapter4-code/eurekasvr
  - TEST_DIR=chapter4-code/licensing-service
  - TEST_DIR=chapter4-code/organization-service
  - TEST_DIR=chapter5-code/confsvr
  - TEST_DIR=chapter5-code/eurekasvr
  - TEST_DIR=chapter5-code/licensing-service
  - TEST_DIR=chapter5-code/organization-service
  - TEST_DIR=chapter6-code/confsvr
  - TEST_DIR=chapter6-code/eurekasvr
  - TEST_DIR=chapter6-code/licensing-service
  - TEST_DIR=chapter6-code/organization-service
  - secure: FCXY0D6T1OiGKgy6aIBJi/cCkVmWaOaNCXqhJmG+2j2+WSFARZJ8m5UFlLkuozV8F3Ka8lZ5+1oZfTcmDP6gr4jk5pfjbIEzXcs+L/wfyyoMqw4SCdJ4EcYOZnV/AmwN9e5nyj5brDJ4Urx/9UIHiKdroL7niz0FOEsa7E3sy3xznRPoriQC4FtJY2RRe7AzrFAJruXxWxpgzkj7+iNL4bHW7G7FM9l9B0XdoMs69a/5oJmjl9uMpii1PGkSY0xMWYx5BEX933dLgv4dsKraR3S+tQTH+FaYOfO8v/esoEQFFQONLriIl4+W5hg1dwEfJ/U5Fxq/pR6Mhmm3H8hZmMvaHxD5ylxD1MhBorqA4GVY+2VSxCYgp2Phc7g61q+cV1jpQPqUv5U9VL19cujthapBVTlxrup5HI66FXWZXGEXFDIte6O0p7chytr+jNWCBhseGUPd4mRxgr9GTUNWC60ejXyqmUAXw4o2nNCC9U7yV2lTDGg2XKK269r5xeTEnmsduJ8n9yfnyRszUtxHotcXApDw04RsTTI7VEs5iYOm7+ER8JeMHht/tQdxsTPu3a6dFDDGqXKZUexLyhNLRjNICRlEweI4lA3NYmRn88X7WPH/rbR6rqIGPH4rcPMiHI62dO9xiVk15uUuIc3mLXtLXDAKpYwa3yLKrTO+bXk=
  - secure: ozeWr+59imfFLVMFtajdjsnhkatpxubNGKyPROUy/3GDySB3/ut1t/7xpl9/GdGmXG3rU1QB/Wl37KbfPzyZPWK64uBvKqbdBwvu2//2jgcNpyfyk7oseDHaByGyjQAd7DsxKHbAKypjIQlDSGgV4Awxl1YTHwZ14twjBoj/jCCo9NMETSu0OVeph19V9vWbS3I7Gnz44QLS7ZiBkjIwiw0SQ2Pz3Dq9p3/0uurrKKVKxF8rbkKFmDegbfEoMeuuyQ9wDzQ5iGTB6SusPHzTk7DMhbZ4IuH1f9Yv9pj1djUIhvM+lhfbpMGT2WN/IGmEBkntRkqDo5VBCErM9Enrsgag+s3LO6nrlwFpKChh/aHHJkIMfvftz0GNDmXzjyWpj3lzkwbMnE97ymFcZBy8EDmvnkO33g/J+KS/++rrqDEZdkqS4yrcGPPHwfaE/suJ5dc1Bna/0HD6VIpAh1WR+9haxp7NFCktARkm+MvtZo0RREaB4rBk6ZXpNlZFQt2F+hwNOxdnaQ8LvJSYcXnx6Ap3n7eG8DDl6eCJGXv0eH4m4/9o4lmomRmy9KczcaGb/cNjWF1UvIj+X1zm/PJu9KxVNfAjsVJpgbvtKHcPHBFvzX2Og+H2rOsolXUbkQJC+MCrzF0fPIY2d4c3xVcNyahEIuU53QK23CmLaY0yvkE=
  - secure: mQRUvojwyohNlOEwSStErAfzrrkBgAcIm43ILWwSXQt9C7+Mf9QCNEcGkdjX+PzC+6ZyjiaLJK1sbyDz/Uklo0Z2osBLwtCgzsSaWS3FvZrq1urWFdTCrOQURG5YvRGKsrQ5cW2wXJaYy3BSw/OLGKF6TbTuoNIsYzeeow2iEn9q4Z0l5kkZS7DdyEHuM+cXJhLQ5WVEyPwX2DeAPdPZPyE9C0+MRwYpt/76bMcrcLc+r/P7rbLWt4cAvTpLCa5YuMNRxXrj3T38v9qi1qZ3O7SSRBuKJQW/xRo2aQEtMesGHZpAW0yXbpPvx4vlhl24YkRNCB5W7Rq3JpDqFPJ7M6cQNGR4u4kCwb5Y3wZaNq92Y2NHFCGV/XF4kyA8SZcBaCcap4hHxT7R005VRAzHy2Aiexbx48O7ZvrxSH1/fCGn1bXq+wT9a5wuFh3QBrCHY5uCumsA30Hl586ICqXgnHhvFkJjUk6i3NdYckfN5QmExDMEVgoJdVNImhirCvEJlZGnhC9bflRyGTZ0nXWfXGkICvdNhYRnKYHtllv/dDZ7oIWr5ByrEo2ZQ5g8t/1bzoX/CjzS2XTqKGjSO/RBvvfN+Vq85OLVVxh8B4iA5vfXV85FcgBbIAki6gZsQklYLUKyMuFuCdLdqZcwiaxbTGUsT/a8XrJdPEZC3MZdnZo=
script:
- cd $TEST_DIR &&  docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD" &&   mvn clean package docker:build
