eurekaserver:
   image:   ch6-thoughtmechanix/eurekasvr
   ports:
       - "8761:8761"

configserver:
    image: ch6-thoughtmechanix/configurationserver
    ports:
       - "8888:8888"
    links:
       - "eurekaserver:eurekaserver"
    environment:
       EUREKASERVER_URI: "http://eurekaserver:8761/eureka/"

zuulserver:
    image: ch6-thoughtmechanix/zuulsvr
    ports:
      - "5555:5555"
    links:
      - "eurekaserver:eurekaserver"
    environment:
      PROFILE: "default"
      SERVER_PORT: "5555"
      EUREKASERVER_URI: "http://eurekaserver:8761/eureka/"

database:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=p0stgr@s
      - POSTGRES_DB=eagle_eye_local

licensingservice:
    image: ch6-thoughtmechanix/licensing-service
    ports:
      - "8080:8080"
      - "8090:8090"
    links:
      - "database:database"
      - "configserver:configserver"
      - "eurekaserver:eurekaserver"
      - "zuulserver:zuulserver"
    environment:
      PROFILE: "default"
      SERVER_PORT: "8080"
      CONFIGSERVER_URI: "http://configserver:8888"
      EUREKASERVER_URI: "http://eurekaserver:8761/eureka/"

organizationservice:
    image: ch6-thoughtmechanix/organization-service
    ports:
      - "8085:8085"
    links:
      - "database:database"
      - "configserver:configserver"
      - "eurekaserver:eurekaserver"
      - "zuulserver:zuulserver"
      - "es:es"
      - "fluentd:fluentd"
    environment:
      PROFILE: "default"
      SERVER_PORT: "8085"
      CONFIGSERVER_URI: "http://configserver:8888"
      EUREKASERVER_URI: "http://eurekaserver:8761/eureka/"

es:
  image: elasticsearch:2
# does not work on mac unless dir owner is elasticsearch
#  volumes:
#    - ${PWD}/es-data:/usr/share/elasticsearch/data
# The following will store es data in your boot2docker vm
# Use 'docker-machine ssh default' to remove it
  volumes:
    - /srv/docker/es:/usr/share/elasticsearch/data
  ports:
    - 9200:9200
    - 9300:9300

kibana:
  image: kibana
  ports:
    - 5601:5601
  links:
    - es:elasticsearch

fluentd:
    image: jcc-fluent
    ports:
      - 24224:24224
      - 9980:9980
    links:
      - es:es

