#spring:
#  application:
#    name: licensingservice
#  profiles:
#    active:
#      default
#  cloud:
#    config:
#      enabled: truecd
##      discovery:
##        enabled: true
##        serviceId: configserver

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
