#Default port is 5555
spring:
  application:
    name: zuulservice

server:
  port: 5555

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
        defaultZone: http://localhost:8761/eureka/

#Setting logging levels
logging:
  level:
    com.netflix: WARN
    org.springframework.web: WARN
    com.thoughtmechanix: DEBUG


zuul:
 # debug:
  #  request: true
  prefix:  /api

#  routes:
#    organization: /organizationservice/**
#    licensing: /licensingservice/**
