configserver:
    image: tmx-confsvr:chapter3
    ports:
       - "8888:8888"
database:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=p0stgr@s
      - POSTGRES_DB=eagle_eye_local
licensingservice:
    image: ch3-thoughtmechanix/licensing-service
    ports:
      - "8080:8080"
    links:
      - "database:database"
      - "configserver:configserver"
    environment:
      PROFILE: "default"
      CONFIGSERVER_URI: "http://configserver:8888"
